### ISSUE TITLE
Filesystem tracking issue

### ISSUE THREAD

**Issue by bugadani** [card-io-ecg/card-io-fw#36]
MVP #32 

Future opportunities and ideas I need but can wait:

 - [ ] GC algo to move blocks of a file
 - [ ] Free up space as needed
 - [ ] File writer API
 - [ ] List files
 - [ ] Allow appending to closed files - reallocates header
 - [ ] Keep space for GC

Future opportunities and ideas I don't immediately need:

 - [ ] Seek while reading
 - [ ] Better estimate size of new metadata object
 - [ ] Rename/move file
 - [ ] Directories
 - [ ] Access multiple files at the same time
 - [ ] Batch multiple small, consecutive writes
 - [ ] Consider supporting odd-byte (3) write granularity
