### ISSUE TITLE
Wifi connectivity/data upload tracking issue

### ISSUE THREAD

**Issue by bugadani** [card-io-ecg/card-io-fw#46]
- #25 
 - [ ] Connect to a configured network
 - [ ] Associate device with user
 - [ ] Store measurement data in RAM
 - [ ] Store measurement in flash if offline
 - [ ] Attempt to upload measurement
